#!/bin/sh
if [ `id -u` -ne 0 ]; then
	echo "this script must be run as root"
	exit 2
fi

dir="$(dirname "$0")"
set -eux
adb forward tcp:41927 tcp:41927
cp "$dir/resolv.conf" /etc/
openvpn --config "$dir/azilink.ovpn"
